//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportCSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public string EmployeeID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string EmployeeAddress { get; set; }
        public string PostalCode { get; set; }
    }
}
